### ISSUE TITLE
Cannot update job status with dci_job

### ISSUE THREAD

**Issue by guillaumevincent** [redhat-cip/dci-ansible#8]
I tried to create a job state for job id xxxxxx

I tried:

```
- name: clean environment
  hosts: localhost
  tasks:
    - include: hooks/clean.yml
      vars:
        dci_status: 'pre-run'
```

and

```
- dci_job:
    id: "xxxxxx"
    status: 'success'
```

None of the two solutions works

**Comment by dsavineau** [comment]
For the first solution you should use :

```
- name: clean environment
  hosts: localhost
  vars:
    dci_status: 'pre-run'
  tasks:
    - include: hooks/clean.yml
```

Because the dci-status need to be a variable of the play for the callback.

For the second solution it doesn't seems to work anymore due to auth token :

```
TASK [dci_job] *********************************
Using module file /usr/share/dci/modules/dci_job.py
ok: [localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "comment": null, 
            "components": [], 
            "configuration": null, 
            "dci_api_secret": null, 
            "dci_client_id": null, 
            "dci_cs_url": null, 
            "dci_login": null, 
            "dci_password": null, 
            "embed": null, 
            "id": "b0faa789-efc3-48bc-a339-ea12cb39040e", 
            "jobdefinition_id": null, 
            "metadata": null, 
            "notify": null, 
            "state": "present", 
            "status": "failure", 
            "team_id": null, 
            "topic": null, 
            "upgrade": null
        }
    }, 
    "message": "(psycopg2.IntegrityError) insert or update on table \"logs\" violates foreign key constraint \"logs_user_id_fkey\"\nDETAIL:  Key (user_id)=(849ee0e2-62fb-4d67-858e-a043ddf10e68) is not present in table \"users\".\n [SQL: 'INSERT INTO logs (id, created_at, user_id, team_id, action) VALUES (%(id)s, %(created_at)s, %(user_id)s, %(team_id)s, %(action)s)'] [parameters: {'action': 'update_job_by_id', 'created_at': '2017-09-06T19:58:42.792345', 'user_id': UUID('849ee0e2-62fb-4d67-858e-a043ddf10e68'), 'team_id': UUID('ddfe879b-71dc-41a6-967c-d3caabaf4943'), 'id': 'c188cbc7-582a-40f2-909c-feebd7a321c5'}]", 
    "payload": {}, 
    "status_code": 400
}
```
This is a know issue reported on the api side : https://github.com/redhat-cip/dci-control-server/issues/43
